defaults:
  - _self_
  - filter: isolate_only

paths:
  metadata: "${hydra:runtime.cwd}/analyses/01_gtdb_reps_analysis/out/2025-12-13_01-13-11/metadata_ex.tsv"
  gtdb_reps_dir: "${hydra:runtime.cwd}/data/gtdb/226.0/genomic_files/reps"

manifest_name: "manifest.csv"

hydra:
  run:
    dir: "${hydra:runtime.cwd}/analyses/02_generate_manifest/out/${now:%Y-%m-%d_%H-%M-%S}"
  output_subdir: config
  job: 
    chdir: True